### ISSUE TITLE
ImportError: cannot import name '_env' from 'cppenv'

### ISSUE THREAD

**Issue by DabeiWang** [wenwenla/tvt2022#1]
This error occurs when I run the sh script.
Can you give me a instruction?
Or provide a python environment

**Comment by wenwenla** [comment]
Do you follow the guide in README?

1. apt update && apt install swig (The version SWIG Version 4.0.1 is ok.)
2. cd env_wrapper
3. ./reinstall

The environment was implemented by cpp, so it must be compiled first, 
Do you see any errors when runing the reinstall script?

**Comment by DabeiWang** [comment]
No errors occur when the reinstall script is run.
I wonder if the data (sl_samples_32.pkl) used by sl_train.py is generated by td3_fast.py?

**Comment by wenwenla** [comment]
Data (samples) used in the supervised learning stage is generated by `model_eval.py`, you can check the code.
To collect samples, we should first use `td3_fast.py` to train the parameters for policy, and then use the policy to collect data.
I'm not sure about the reason for the import error, could you please tell me more details, such as the version of swig and python, and the compute platform (windows or linux).
Our code was originally tested in ubuntu 16.04.

**Comment by DabeiWang** [comment]
I commented out "from cppenv import _env" and it worked. I have some questions about this project:
1. Running the `PS_train_td3_baseline.sh`, the first phase of training will be a model of the global (gy2) and the local (ly2) types of the bureau. This step is running `td3_fast.py`.
2. Run `model_eval.py` to evaluate the model for (1). In this step, the models used for evaluation are `ly2/td3_32/models/40001.pkl `(generating` new_version/l32_data.pkl`), The models used to collect data are `gy2/td3_32/models/40001.pkl` (generate `new_version/sl_samples_32.pkl`)
3. Run `sl_train.py`, `PATH = 'new_version/sl_samples_32.pkl' MODEL_PATH = 'new_version/sl_models_32'`, `new_version/sl_models_32/model_199.pkl` is generated. The terminal displays` Loss: nan, Test Loss RMSE: nan `from beginning to end.
4. Run `model_eval_sl.py`, `SL_MODEL_PATH = './new_version/sl_models_32/model_199.pkl ', /new_version/27601_g_32.pkl ', OUTPUT_PATH = './new_version/gl32_data_sl.pkl '`, I wonder if `policy_path` is `gy2/td3_32/models/40001.pkl`? What should the `Output_path` be? I set it to `'./new_version/l32_data.pkl '`and output `{'uav_0': nan, 'uav_1': nan, 'uav_2': nan, 'uav_3': nan, 'uav_4': nan, 'uav_5': nan, 'uav_6': nan, 'uav_7': nan, 'uav_8': nan, 'uav_9': nan, 'uav_10': nan, 'uav_11': nan, 'uav_12': nan, 'uav_13': nan, 'uav_14': nan, 'uav_15': nan, 'uav_16': nan, 'uav_17': nan, 'uav_18': nan, 'uav_19': nan, 'uav_20': nan, 'uav_21': nan, 'uav_22': nan, 'uav_23': nan, 'uav_24': nan, 'uav_25': nan, 'uav_26': nan, 'uav_27': nan, 'uav_28': nan, 'uav_29': nan, 'uav_30': nan, 'uav_31': nan}R={'uav_0': nan, 'uav_1': nan, 'uav_2': nan, 'uav_3': nan, 'uav_4': nan, 'uav_5': nan, 'uav_6': nan, 'uav_7': nan, 'uav_8': nan, 'uav_9': nan, 'uav_10': nan, 'uav_11': nan, 'uav_12': nan, 'uav_13': nan, 'uav_14': nan, 'uav_15': nan, 'uav_16': nan, 'uav_17': nan, 'uav_18': nan, 'uav_19': nan, 'uav_20': nan, 'uav_21': nan, 'uav_22': nan, 'uav_23': nan, 'uav_24': nan, 'uav_25': nan, 'uav_26': nan, 'uav_27': nan, 'uav_28': nan, 'uav_29': nan, 'uav_30': nan, 'uav_31': nan}, TA=0, D=0, DTC=[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
`

I think step3 and step4 are wrong.
I would like to know how to use your code correctly.
Thank you very much.

**Comment by wenwenla** [comment]
Do you mean you have completed the reinforcement learning stage?

1. Could you please show me `tensorboard` logs or run `evaluation-fast.ipynb` and give me an evaluation result of reinforcement learning models? I don't know if you get an effective reinforcement learning policy.
2. Could you please uncomment the print statements in `model_eval.py` and give me the output? Do you modify anything in `model_eval.py` such as the file path in the `collection_data` function?
3. You can find the download link for the reinforcement learning models in README. Can you get correct results using the pre-trained RL models to collect data?

Thank you.

**Comment by DabeiWang** [comment]
Yes, I have finished the RL stage. 
I comment  ` if __package__ or "." in __name__:     from . import _env else:     import _env`   in `pytroch112/lib/python3.8/site-packages/cppenv-0.1-py3.8-linux-x86_64.egg/cppenv/env.py`
1.
![image](https://user-images.githubusercontent.com/129392547/236203193-d0412202-cd50-4efe-a2fe-7991cb0c0e4c.png)
2. I set `EVAL_PATH = ./0426/ly2/td3_32/models/40001.pkl` `COLL_PATH = ./0426/gy2/td3_32/models/40001.pkl` in `model_eval.py`. When I uncomment the print, `AttributeError: EnvWrapper object has no attribute get_reward_split`. So I comment `print(fRS: {self._env.get_reward_split()})`. 
The output is `--99--==========
CNT: 0
Die: 0
Dtc: [665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459, 665.4255728791459]
R: {uav_0: -229.23417017673833, uav_1: -250.0, uav_2: -250.0, uav_3: -250.0, uav_4: -250.0, uav_5: -250.0, uav_6: -250.0, uav_7: -250.0, uav_8: -250.0, uav_9: -236.5808175091037, uav_10: -250.0, uav_11: -308.7500633956015, uav_12: -250.0, uav_13: -197.06443913200536, uav_14: -250.0, uav_15: -250.0, uav_16: -250.0, uav_17: -250.0, uav_18: -250.0, uav_19: -308.7500633956015, uav_20: -247.85885814345656,uav_21: -250.0, uav_22: -250.0, uav_23: -250.0, uav_24: -250.0, uav_25: -250.0, uav_26: -250.0, uav_27: -198.3791365130838, uav_28: -222.10386710693393, uav_29: -250.0, uav_30: -90.65895188878653, uav_31: -234.94732397093873}
MeanTA: 0.0±0.0
MeanDie: 0.02±0.19899748742132398`
3.  I haven't tried yet. But I am not sure if my path is correct, because the code and name of the model you provided do not match. So I just wanted to know if the path Settings for step3 and step4 are correct.

**Comment by wenwenla** [comment]
**Something went wrong in the data collection process, and I don't think it is a path-setting problem.**
As shown in the first picture, you got similar results in our paper Fig.6. in the scenario of 16 agents.
But in the logs, the performance is really bad with average rewards of -250.
I notice that the first plot is about 16 agents, and the data collection process is about 32 agents.
Could you please use `evaluation-fast.ipynb` to get the rewards of 32 agents?
Otherwise, you can first try using `0426/gy2/td3_16/models/32801.pkl` to generate samples in the 16 agents scenario. (As shown in the first picture, model 32801 achieves the highest rewards).
**It is not the case long training will provide better results, so you should first check if model 40001 is a effective policy.**

Here is a code example:

```python
def collect_data():
    agent = EvalAgent(16)  # 16 agents
    agent.setGlobal(True)  # we need the flocking center
    agent.load('0426/gy2/td3_16/models/32801.pkl')
    for i in range(1000):
        agent.eval_one_ep()
        print(f'EP: {i} DL: {len(data_collection)}')

        if len(data_collection) > 500000:
            break

    with open('new_version/sl_samples_16.pkl', 'wb') as f:
        pickle.dump(data_collection, f)
```

**Comment by wenwenla** [comment]
> I wonder if policy_path is gy2/td3_32/models/40001.pkl? What should the Output_path be?

The policy path should be the model path you used to collect data in the second step and make sure you set the number of agents correctly.
The Output_path can be anything you want, just make sure the folder exists.

**Comment by DabeiWang** [comment]
I just realized that the training of the 32 agents seems to have failed
![image](https://user-images.githubusercontent.com/129392547/236606159-85add919-b238-45e2-9032-67ff3540bbfe.png)
I retrained yesterday and found that the newly generated strategy also failed
![image](https://user-images.githubusercontent.com/129392547/236607435-707d7f9d-a34e-4160-b22c-84128badbf64.png)

**Comment by wenwenla** [comment]
A suggestion is to retrain the two models for 32 agents scenario. 
I use exactly the same hyperparameters to train the policy.
The training process might be unstable when large numbers of agents are involved.
Maybe I should fix all randomness in the training process.
Or you can just try our pretrained models.

Another solution is that you can use the *best* policy you have got to do the next evaluation.

**Comment by DabeiWang** [comment]
I have retrained (0505), using the best strategy (`/0505/gy2/td3_32/models/8001.pkl`) to collect data, yet the output of training in phase 2 is still `nan`
```
Loss: nan, Test Loss RMSE: nan
77...
Loss: nan, Test Loss RMSE: nan
78...
Loss: nan, Test Loss RMSE: nan
79...
Loss: nan, Test Loss RMSE: nan
80...
Loss: nan, Test Loss RMSE: nan
```
I've tested your pretrained model, and it works well.
I will try again to train 32 agents for the scenario.
You said "I use exactly the same hyperparameters to train the policy."，are the hyperparameters you use the same as those in the code?

**Comment by wenwenla** [comment]
Yes, the hyperparameters I used are the same as those in the code.
I think the only reason for the difference is the randomness during exploration.

**Comment by DabeiWang** [comment]
I use the best policies, such as` 0426/gy2/td3_32/models/38801.pkl` in Fig2 and` 0505/gy2/td3_32/models/8001.pkl`  in Fig3, to collect data, but the second phase of training is still `nan`.

How can I solve this problem? Should I go back to the first phase of training?

**Comment by wenwenla** [comment]
What are the outputs when collecting data? 
Maybe you should analyze the collected data first, and find if anything abnormal in the data.
I think it's a data-related issue, but not a supervised-learning-related issue.
You said that you have tested the pre-trained model.
Does this mean the data collected by the pre-trained model can be used to successfully train the supervised learning model?

**Comment by DabeiWang** [comment]
when collecting data， the output is `with open('new_version/sl_samples_16.pkl', 'wb') as f: pickle.dump(data_collection, f)`
How do I determine if the collected data is abnormal?

The data I collected with the pre-training model was used for the second stage of training and evaluation, and no `nan` output appeared.

**Comment by wenwenla** [comment]
I mean text output, such as rewards and MeanTA, please uncomment the print statements when collecting data.

you can use the following code to check the data.
```python
with open('new_version/sl_samples_16.pkl', 'rb') as f:
    data = pickle.load(f)
print(data)
```

Check if there are any nans in the collected data.
Or you can just paste part of the outputs here, I will help you find if there are any uncommon things in the data.
